---
- name: Clone a private repository into dir 'fin'
  git:
    repo: git@github.com:toidiu/fin.git
    version: master
    dest: fin
    accept_hostkey: yes
  # ssh-agent doesn't allow key to pass through remote sudo commands.
  become: no

- name: Build fin server -- release
  command: chdir=~/fin/service {{ item }}
  with_items:
  - cargo build --release
