---
- name: copy the nginx config file and restart nginx
  become: yes
  copy:
    src: nginx_website.cfg
    dest: /etc/nginx/sites-available/fin_site.cfg

- name: create symlink
  become: yes
  file:
    src: /etc/nginx/sites-available/fin_site.cfg
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: start nginx
  become: yes
  service:
    name: nginx
    state: started

- name: restart nginx
  become: yes
  service:
    name: nginx
    state: restarted

