---
- hosts: fin

  vars_files:
    - vars/main.yml

  # roles run before task.. so this doesnt work on a new machine.
  # must comment out and do init tasks first. fix is to make roles
  # out of pre and post tasks
  roles:
    - hurricanehrndz.rustup

  tasks:
    # --------------
    # -------------- INIT SERVER
    # --------------
    - name: Set timezone to UTC
      timezone:
        name: UTC
      become: yes
      become_method: sudo

    # --------------
    # -------------- APT
    # --------------
    - name: Nginx setup
      import_tasks: tasks/apt.yml

    # --------------
    # -------------- Dotfiles
    # --------------
    - name: Clone dotfile repo
      git:
        repo: 'https://github.com/toidiu/dotfiles.git'
        dest: ~/.dotfiles
        version: master
        force: yes

    # - name: Run setup dotfiles
    #   shell: ~/.dotfiles/setup.sh -y

    # --------------
    # -------------- APPLICATION
    # --------------
    - name: Clone a private repository into dir 'fin'
      git:
        repo: git@github.com:toidiu/fin.git
        version: master
        dest: fin
        accept_hostkey: yes
        force: yes

    - name: Build website
      import_tasks: tasks/website.yml

    - name: Build rust server
      import_tasks: tasks/rust.yml

    # --------------
    # -------------- NGINX
    # --------------
    - name: Nginx setup
      import_tasks: tasks/nginx.yml



