[app]
paseto_token = "________________________________"
cors_origin = "http://fin.toidiu.com"

[database]
url = "postgres://___:___:@localhost:5432/fin-prod"

[iex]
token = "___________________________________"
debug = false
